name: xhydro_lstm
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.13
  - charset-normalizer >=3.1.0
  - netcdf4 # Pinning in RavenPy and xhydro complicate the versioning here.
  - numpy >=1.25.0
  - scikit-learn >=1.2.0
  # - tensorflow # "Do not install TensorFlow with conda. It may not have the latest stable version. pip is recommended since TensorFlow is only officially released to PyPI."
  - xarray >=2023.11.0
  - xhydro
  # Dev tools and testing
  - pip >=26.0.1
  - bump-my-version >=1.3.0
  - codespell >=2.4.2
  - coverage >=7.5.0
  - deptry >=0.25.1
  - flake8 >=7.3.0
  - flake8-rst-docstrings >=0.4.0
  - flit >=3.11.0,<4.0
  - mypy >=1.20.0
  - numpydoc >=1.10.0
  - prek >=0.3.0
  - pytest >=9.0.2
  - pytest-cov >=7.0.0
  - ruff >=0.15.9
  - tox >=4.52.0
  - tox-gh >=1.7.1
  - vulture >=2.14
  - watchdog >=6.0.0
